### PR TITLE
[CS2113T]-sinteary-BugFixesAndImprovements

### LINKED ISSUE #216: Warn users against adding duplicate tasks/members
To avoid repetition, and also to allow the HashMaps to work properly. Currently, task and member use hashcodes that confirm the following in order for assignments to work properly: 
Member: all details
Task: task name, credit and priority
This is important as it might affect the hashing function as shown below:

image

### LINKED ISSUE #264: unhandled exception for delete member command
unhandled exception for delete member command

<hr><sub>[original: LL-Pengfei/ped#9]<br/>
</sub>

### LINKED ISSUE #265: unhandled exception for deleting project - non-integer index
unhandled exception for deleting project - non-integer index

<hr><sub>[original: LL-Pengfei/ped#10]<br/>
</sub>

### LINKED ISSUE #269: NumberFormatException not handled
If the user type invalid input for number, for example aphabet or large numbers, the exception must be handled.

<hr><sub>[original: JokerYan/ped#2]<br/>
</sub>

### LINKED ISSUE #272: Confusing when showing credits for different members of the same name
Since it allows different members of the same name, it is confusing to display only the name when displaying credits. It is hard to know which member is which.

<hr><sub>[original: JokerYan/ped#5]<br/>
</sub>

### LINKED ISSUE #292: Empty parameters in assign task crashes the program
As seen above, a missing parameter crashes the program. An exception or a proper error message should really be given and not let the program crash, because when the program crashes, nothing is saved. So... as a user it becomes extremely tedious for all my work to be gone because i missed out one parameter...

Occurs in assignments as well

<hr><sub>[original: matthewng1996/ped#9]<br/>
</sub>

### LINKED ISSUE #297: [AY1920S1-CS2113-T13-1] Didn't catch for big integer exception
<hr><sub>[original: valerietyj/ped#3]<br/>
</sub>

### LINKED ISSUE #308: [AY1920S1-CS2113-T13-1] Never catch exception for blank input
Never catch exception properly when blank input during first start 

<hr><sub>[original: valerietyj/ped#15]<br/>
</sub>

### LINKED ISSUE #315: Delete multiple tasks at once
It is tedious to delete tasks one by one, so it might be easier to delete multiple tasks at once.
Take note that order matters:
Eg. if there are 2 tasks and I want to delete both of them: task 2 must be deleted before task 1 to avoid shifting of index numbers.

### LINKED ISSUE #316: Delete multiple members at once

### PR DESCRIPTION
**Pull request by sinteary**
Fix some bugs regarding invalid inputs.
Manage/delete projects: 
Resolve #265 
Resolve #297 
Resolve #308
Delete task: Resolve #269
Delete member: Resolve #264
Assign task: Resolve #292

Avoid adding duplicate members and tasks:
Resolve #216 
Resolve #272 
Allow deleting multiple members/tasks in the same command: 
Resolve #315 
Resolve #316

### CODE REVIEW

File: src/main/java/controllers/ConsoleInputController.java [hunk 1]
```diff
@@ -34,7 +34,12 @@ public ConsoleInputController(ProjectRepository projectRepository) {
     public String[] onCommandReceived(String input) {
         ArchDukeLogger.logInfo(ConsoleInputController.class.getName(), "User input: '" + input + "'");
         Scanner inputReader = new Scanner(input);
```
Comment (sinteary) [inline src/main/java/controllers/ConsoleInputController.java]: This resolves #308

File: project.json [hunk 2]
```diff
@@ -0,0 +1,23 @@
+{
```
Comment (Lucria) [inline project.json]: Please don't commit the json file next time

File: src/main/java/models/member/Member.java [hunk 3]
```diff
@@ -32,9 +32,7 @@ public boolean equals(Object obj) {
             return false;
         } else {
             Member other = (Member) obj;
-            return this.name.equals(other.name)
-                && this.phone.equals(other.phone)
-                && this.email.equals(other.email);
+            return this.name.equals(other.name);
         }
```
Comment (Lucria) [inline src/main/java/models/member/Member.java]: What's the reason for this change?

Comment (sinteary) [reply src/main/java/models/member/Member.java]: Previously the hashing function made it such that members with the same name could be added, which could cause confusion. Furthermore it could result in problematic distribution of credits (as mentioned in issue #282 To prevent this, we ensure that members must have different names.

File: project.json (hunk 2 above)
Comment (sinteary) [reply project.json]: ok!

File: src/test/java/controllers/ProjectInputControllerTest.java [hunk 4]
```diff
@@ -144,23 +194,23 @@ void testProjectViewCredits() {
...
 
     @Test
-    void testProjectAddTask() {
+    void testProjectAddTask_valid() {
         try {
             Project project = new Project("Infinity_Gauntlet");
             dueDate = dateTimeHelper.formatDate("21/09/2019");
             simulatedUserInput = "add task -t Documentation for product -p 2 -d 21/09/2019 -c 40 -s todo "
                     + "-r do something -r do another thing";
             projectInputController.projectAddTask(project, simulatedUserInput);
```
Comment (sinteary) [inline src/test/java/controllers/ProjectInputControllerTest.java]: Simply changed the task name here because I edited it such that tasks with the same name cannot be added.

File: src/main/java/models/member/Member.java (hunk 3 above)
Comment (iamabhishek98) [reply src/main/java/models/member/Member.java]: yeap, seems like a logical explanation

File: src/test/java/controllers/ProjectInputControllerTest.java (hunk 4 above)
Comment (iamabhishek98) [reply src/test/java/controllers/ProjectInputControllerTest.java]: i am not sure i understand the reason for this change. Does it mean only positive test cases can be under that method?

Comment (sinteary) [reply src/test/java/controllers/ProjectInputControllerTest.java]: Yup. I think so. I'm trying to follow the format seen in the notes as shown here:
image
Here's the associated page in the textbook
https://nuscs2113-ay1920s1.github.io/website/se-book-adapted/chapters/junit.html#junit

Comment (iamabhishek98) [reply src/test/java/controllers/ProjectInputControllerTest.java]: alrite got it
