### PR TITLE
[CS2113-T13-1]-seanlimhx-FixedBugsInEditTaskRequirements

### LINKED ISSUE #280: Crashes when setting task requirement without the requirement specified
When setting requirements for the task, it will crash the program if the `-r` option not specified. It should report invalid command instead

<hr><sub>[original: JokerYan/ped#13]<br/>
</sub>

### LINKED ISSUE #294: Edit Task Requirements input (Exceptions could be added)
From the screenshot, a index 4 that does not exist is still accepted by the program

Likewise, index 0 is accepted by the program.

A negative index crashes the program.

Apart from negative index, having invalid index does not affect main functions.

<hr><sub>[original: matthewng1996/ped#11]<br/>
</sub>

### LINKED ISSUE #312: [AY1920S1-CS2113-T13-1] Never handle exceptions correctly
<hr><sub>[original: valerietyj/ped#19]<br/>
</sub>

### LINKED ISSUE #313: Task Requirements issue
Bug in add and edit task requirements: 

<hr><sub>[original: valerietyj/ped#20]<br/>
</sub>

### PR DESCRIPTION
**Pull request by seanlimhx**
image
image
image
image
image

Now able to:
Catch if input is missing a task index
catch if input task index is invalid
catch empty flags (i.e. flags without any subsequent information)
catch invalid flags (only allow -r and -rm)
use multiple -rm flags in one command
catch if user inputs multiple same index

Resolve #313 
Resolve #312 
Resolve #294 
Resolve #280

### CODE REVIEW

File: src/main/java/controllers/ProjectInputController.java [hunk 1]
```diff
@@ -333,18 +333,25 @@ public ProjectInputController(ProjectRepository projectRepository) {
...
-            String updatedTaskRequirements = projectCommand.substring(projectCommand.indexOf("-"));
+            int taskIndexNumber = Integer.parseInt(projectCommand.substring(23).trim().split(" ")[0]);
             if (projectToManage.getNumOfTasks() >= taskIndexNumber && taskIndexNumber > 0) {
-                projectToManage.editTaskRequirements(taskIndexNumber,updatedTaskRequirements);
-                return new String[] {"The requirements of your specified task has been updated!"};
+                if (!projectCommand.contains("-")) {
+                    return new String[] {"No flags are found! Please use flags such as '-r' or '-rm' to indicate "
+                            + "the new requirements to be added or removed! Refer to the user guide for more help!"};
+                } else {
+                    String updatedTaskRequirements = projectCommand.substring(projectCommand.indexOf("-"));
```
Comment (sinteary) [inline src/main/java/controllers/ProjectInputController.java]: Might have an error here if the line does not contain "-"!

Comment (seanlimhx) [reply src/main/java/controllers/ProjectInputController.java]: if the line doesn't have "-",  it will enter the if block and return the message that no flags are found

File: src/main/java/models/task/TaskList.java [hunk 2]
```diff
@@ -147,46 +147,117 @@ public int getSize() {
...
+        ArrayList<String> errorMessages = new ArrayList<>();
+        errorMessages.add("Errors...");
+
         ArrayList<String> newTaskRequirementDetails = parserHelper.parseTaskRequirementDetails(updatedTaskRequirements);
+
+        if ("No error".equals(newTaskRequirementDetails.get(0))) {
+            newTaskRequirementDetails.remove(0);
+        } else {
+            while (!"Errors end".equals(newTaskRequirementDetails.get(0))) {
+                errorMessages.add(newTaskRequirementDetails.get(0));
```
Comment (sinteary) [inline src/main/java/models/task/TaskList.java]: Not sure about your implementation here, but ParserHelper itself has an ArrayList<String> that can help you store any error messages in parsing. You can simply call ParserHelper.getErrorMessages() to get all the messages, so that could possibly save you some work here?

File: src/main/java/models/task/TaskList.java [hunk 3]
```diff
@@ -147,46 +147,117 @@ public int getSize() {
...
-                //input validation if input index to be removed does not exist, but currently does not show mistake to
-                // user
-                this.taskList.get(taskIndexNumber - 1).removeTaskRequirement(indexToBeRemoved);
+            try {
+                int indexToBeRemoved = Integer.parseInt(indexesToBeRemoved[i]);
+                if (indexToBeRemoved > 0
+                        && indexToBeRemoved <= startingNumOfTaskRequirements) {
+                    if (!listOfUsedIntegers.contains(indexToBeRemoved)) {
+                        successMessages.add("'"
+                                + this.taskList.get(taskIndexNumber - 1).getTaskRequirements().get(indexToBeRemoved)
```
Comment (sinteary) [inline src/main/java/models/task/TaskList.java]: I think there might be an error here. TaskList.get(task index) already accounts for the -1 if I'm not wrong!
image

File: src/main/java/models/task/TaskList.java (hunk 2 above)
Comment (seanlimhx) [reply src/main/java/models/task/TaskList.java]: it's because i'm returning a single String array back so i use that as an indicator to separate the error messages and the new task requirement details

Comment (sinteary) [reply src/main/java/models/task/TaskList.java]: Oops ok I see that you are already using the errorMessages array! Sorry about this!

Comment (seanlimhx) [reply src/main/java/models/task/TaskList.java]: oh damn i didn't know, thanks i'll go change it

File: src/main/java/models/task/TaskList.java (hunk 3 above)
Comment (seanlimhx) [reply src/main/java/models/task/TaskList.java]: oh this one i used the get() method from ArrayList class, not the getTask() function
